src/AppBundle/Entity/RoleRepository.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	public function getRoleClient()
	{
		$qb = $this->createQueryBuilder('r')
		    ->where('r.nom = :name' )
		    ->setParameters(array('name' => 'Client'));

		return $qb
		    ->getQuery()
		    ->getResult();
	}

	public function getRoles()
	{
		$qb = $this->createQueryBuilder('r');

		return $qb
		    ->getQuery()
		    ->getResult();
	}
}

src/AppBundle/Resources/views/Admin/addcontact.html.twig
{# src/AppBundle/Resources/views/Admin/addcontact.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Admin - Ajouter compte
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
        	<li><a href="{{ path('accueil_admin') }}">Administration</a></li>
        	<li class="active"><a href="{{ path('ajouter_contact') }}">Ajout contact</a></li>
        </ol>
{% endblock %}

{% block menu %}
	{{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
	<div id="cadrebody">
		<h3>Ajout d'un contact</h3>

		<div class="well">
  		{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  			{{ form_errors(form) }}

		    <div class="form-group">

		      {{ form_label(form.societe, "Contact pour la société", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.societe) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.societe, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.nomContact, "Nom", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.nomContact) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.nomContact, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.prenomContact, "Prénom", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.prenomContact) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.prenomContact, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>	

		    <div class="form-group">

		      {{ form_label(form.intitulePoste, "Poste dans la société", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.intitulePoste) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.intitulePoste, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.telFixe, "Téléphone fixe", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.telFixe) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.telFixe, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.telMobile, "Téléphone mobile", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.telMobile) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.telMobile, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.fax, "Numéro de fax", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.fax) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.fax, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.email, "Adresse mail", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.email) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.adresse, "Adresse", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.adresse) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>	

		    <div class="form-group">

		      {{ form_label(form.codePostal, "Code postal", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.codePostal) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.codePostal, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.ville, "Ville", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.ville) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.pays, "Pays", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.pays) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.pays, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.commentaire, "Commentaires", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.commentaire) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.commentaire, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>
		    		    
		    <div id="submitform">
		    	{{ form_widget(form.valider, {'attr': {'class': 'btn btn-primary'}}) }}
		        {{ form_widget(form.annuler, {'attr': {'class': 'btn btn-default'}}) }}
		    </div>

 			{{ form_rest(form) }}

	  		{# Fermeture de la balise <form> du formulaire HTML #}
	  		{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

src/AppBundle/Resources/views/Admin/compte.html.twig
{# src/AppBundle/Resources/views/Admin/index.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Admin - Gérer compte
{% endblock %}

{% block javascripts %}
  {{ parent() }}

  <script src="{{ asset('js/admin-gerer-compte.js') }}" type="text/javascript"></script>
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
        	<li><a href="{{ path('accueil_admin') }}">Administration</a></li>
        	<li class="active">Gérer compte</li>
        </ol>
{% endblock %}

{% block menu %}
	{{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
	<div id="cadrebody">
		<h3>Sélection du compte</h3>

		<div class="selection">
			<select id="selsociete" class="form-control sel-largeur">
		        <option value="-1" selected>Choisissez une société</option>
		        {% for societe in listesociete %}
		            <option value="{{ societe.idtSociete }}">{{ societe.nomSociete }}</option>
		        {% endfor %}
    		</select>
		</div>

		<div id="selcontact" class="selection" data-path="{{ path('selection_contact') }}">
			<select id="selectcontact" class="form-control sel-largeur">
    			<option value="-1" selected>--------</option>
			</select>
		</div>

		<div id="formutilisateur" data-path="{{ path('form_compte') }}">
		</div>
	</div>
{% endblock %}

src/AppBundle/Resources/views/Admin/contact.html.twig
{# src/AppBundle/Resources/view/Admin/contact.html.twig #}

<h3>Contacts</h3>

<table id="tabliste">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
            <th>Numéro Fixe</th>
            <th>Détails</th>
            <th>Compte</th>
        </tr>
    </thead>

    <tbody>
        {% for ligne in listecontact %}
            <tr>
                <td>{{ ligne.nomContact }}</td>
                <td>{{ ligne.prenomContact }}</td>
                <td>{{ ligne.email }}</td>
                <td>{{ ligne.telFixe }}</td>
                <td>
                    <a href="{{ path('contact_details', { 'id': ligne.idtContact }) }}">
                        <img class="iconeaction" alt="Détails" src="{{ asset('images/loupe.png') }}">
                    </a>
                </td>
                <td>
                    <a href="{{ path('utilisateur', { 'type': 'compte', 'id': ligne.idtContact }) }}">
                        <img class="iconeaction" alt="Compte" src="{{ asset('images/preference.png') }}">
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>

    <tfoot>
    </tfoot>
</table>

<div id="detailsDuContact">

</div>

src/AppBundle/Resources/views/Admin/details.html.twig
{# src/AppBundle/Resources/views/Admin/details.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Admin - Détails contact
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
        	<li><a href="{{ path('accueil_admin') }}">Administration</a></li>
        	<li class="active"><a href="{{ path('contact_details', { 'id': id }) }}">Détails contact</a></li>
        </ol>
{% endblock %}

{% block menu %}
	{{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
	<div id="cadrebody">
		<h3>Détails d'un contact</h3>

		<div class="well">
  		{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  			{{ form_errors(form) }}

		    <div class="form-group">

		      {{ form_label(form.societe, "Contact pour la société", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.societe) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.societe, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.nomContact, "Nom", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.nomContact) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.nomContact, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.prenomContact, "Prénom", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.prenomContact) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.prenomContact, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>	

		    <div class="form-group">

		      {{ form_label(form.intitulePoste, "Poste dans la société", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.intitulePoste) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.intitulePoste, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.telFixe, "Téléphone fixe", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.telFixe) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.telFixe, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.telMobile, "Téléphone mobile", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.telMobile) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.telMobile, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.fax, "Numéro de fax", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.fax) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.fax, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.email, "Adresse mail", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.email) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.adresse, "Adresse", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.adresse) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>	

		    <div class="form-group">

		      {{ form_label(form.codePostal, "Code postal", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.codePostal) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.codePostal, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.ville, "Ville", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.ville) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.pays, "Pays", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.pays) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.pays, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.commentaire, "Commentaires", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.commentaire) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.commentaire, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>
		    		    
		    <div id="submitform">
		    	{{ form_widget(form.valider, {'attr': {'class': 'btn btn-primary'}}) }}
		        {{ form_widget(form.annuler, {'attr': {'class': 'btn btn-default'}}) }}
		    </div>

 			{{ form_rest(form) }}

	  		{# Fermeture de la balise <form> du formulaire HTML #}
	  		{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

src/AppBundle/Resources/views/Admin/droits.html.twig
{# src/AppBundle/Resources/views/Admin/index.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Admin - Gérer droits
{% endblock %}

{% block javascripts %}
  {{ parent() }}

  <script src="{{ asset('js/admin-gerer-compte.js') }}" type="text/javascript"></script>
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
        	<li><a href="{{ path('accueil_admin') }}">Administration</a></li>
        	<li class="active">Gérer droits</li>
        </ol>
{% endblock %}

{% block menu %}
	{{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
	<div id="cadrebody">
		<h3>Sélection du compte</h3>

		<div class="selection">
			<select id="selsociete" class="form-control sel-largeur">
		        <option value="-1" selected>Choisissez une société</option>
		        {% for societe in listesociete %}
		            <option value="{{ societe.idtSociete }}">{{ societe.nomSociete }}</option>
		        {% endfor %}
    		</select>
		</div>

		<div id="selcontact" class="selection" data-path="{{ path('selection_contact') }}">
			<select id="selectcontact" class="form-control sel-largeur">
    			<option value="-1" selected>--------</option>
			</select>
		</div>

		<div id="formutilisateur" data-path="{{ path('form_droits') }}">
		</div>

	</div>
{% endblock %}

src/AppBundle/Resources/views/Admin/form_compte.html.twig
{# src/AppBundle/Resources/view/Admin/form_compte.html.twig #}

<h3>Utilisateur</h3>

		<div class="well">
		<br>
  		{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  			{{ form_errors(form) }}

		    <div class="form-group">

		      {{ form_label(form.username, "Nom d'utilisateur", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.username) }}

		      <div class="col-sm-4">
		        {# Génération de l'input. #}
		        {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.email, "Adresse Email", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.email) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.isActive, "Compte actif", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.isActive) }}

		      <div class="col-sm-1">
		        {{ form_widget(form.isActive, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

		    <div class="form-group">

		      {{ form_label(form.mdpTemp, "Nouveau mot de passe", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

		      {{ form_errors(form.mdpTemp) }}

		      <div class="col-sm-4">
		        {{ form_widget(form.mdpTemp, {'attr': {'class': 'form-control'}}) }}
		      </div>
		    </div>

  			<br>
		    <div id="submitform">
		    	{{ form_widget(form.modifier, {'attr': {'class': 'btn btn-primary unique-taille'}}) }}
		    	{% if isdroit == true %}
		    		{{ form_widget(form.droit, {'attr': {'class': 'btn btn-primary unique-taille'}}) }}
		    	{% endif %}
		        {{ form_widget(form.annuler, {'attr': {'class': 'btn btn-default unique-taille'}}) }}
		    </div>

 			{{ form_rest(form) }}

	  		{# Fermeture de la balise <form> du formulaire HTML #}
	  		{{ form_end(form) }}
		</div>

src/AppBundle/Resources/views/Admin/form_droits.html.twig
{# src/AppBundle/Resources/view/Admin/form_droits.html.twig #}

<h3>Droits</h3>

{% set tabroles = [] %}
{% for role in utilisateur.roles %}
	{% set tabroles = tabroles|merge([role.id]) %}
{% endfor %}

<div class="well">
	<h4>Utilisateur : <small>{{ utilisateur.username }}</small></h4>
	<br>

	<form name="appbundle_droits" method="post" action="{{ path('form_droits', { 'id': utilisateur.id }) }}" class="form-horizontal">
	
	<h5>Droits rapide</h5>

	{% for ligne in droits %}
		{% if ligne.categorie == 'Utilisateur' %}
	    <div class="form-group">
	        <label class="col-sm-3 control-label required" for="appbundle_droits_{{ ligne.id }}">{{ ligne.nom }}</label>
      		<div class="col-sm-4">
      		{% if ligne.id in tabroles %}
        		<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control" checked>
      		{% else %}
      			<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control">
      		{% endif %}
      		</div>
    	</div>
    	{% endif %}
	{% endfor %}

	<h5>Accès Web</h5>

	{% for ligne in droits %}
		{% if ligne.categorie == 'Accès' %}
	    <div class="form-group">
	        <label class="col-sm-3 control-label required" for="appbundle_droits_{{ ligne.id }}">{{ ligne.nom }}</label>
      		<div class="col-sm-4">
      		{% if ligne.id in tabroles %}
        		<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control" checked>
      		{% else %}
      			<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control">
      		{% endif %}
      		</div>
    	</div>
    	{% endif %}
	{% endfor %}

	<h5>Configuration avancée</h5>

	{% for ligne in droits %}
		{% if ligne.categorie == 'Avancée' %}
	    <div class="form-group">
	        <label class="col-sm-3 control-label required" for="appbundle_droits_{{ ligne.id }}">{{ ligne.nom }}</label>
      		<div class="col-sm-4">
      		{% if ligne.id in tabroles %}
        		<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control" checked>
      		{% else %}
      			<input type="checkbox" id="appbundle_droits_{{ ligne.id }}" name="appbundle_droits[{{ ligne.id }}]" class="form-control">
      		{% endif %}
      		</div>
    	</div>
    	{% endif %}
	{% endfor %}

		<br>

	    <div id="submitform">
	    	<button type="submit" id="appbundle_utilisateur_valider" name="btnvalider" class="btn btn-primary unique-taille">Valider</button>
	        <button type="submit" id="appbundle_utilisateur_annuler" name="btnannuler" class="btn btn-default unique-taille">Annuler</button>
	    </div>
	</form>
</div>

src/AppBundle/Resources/views/Admin/index.html.twig
{# src/AppBundle/Resources/views/Admin/index.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Console administrateur
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
        	<li class="active"><a href="{{ path('accueil_admin') }}">Administration</a></li>
        </ol>
{% endblock %}

{% block menu %}
	{{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
	<div id="cadrebody">
		<h3>Administration</h3>

		<table id="tabliste">
			<thead>
				<tr>
					<th>Nom</th>
					<th>Adresse</th>
					<th>Code postal</th>
					<th>Ville</th>
					<th>Pays</th>
					<th>Commentaire</th>
				</tr>
			</thead>

			<tbody>
				{% for societe in listesociete %}
					<tr name='societe' id='{{ societe.idtSociete }}'>
						<td>{{ societe.nomSociete }}</td>
						<td>{{ societe.adresse1 }}</td>
						<td>{{ societe.codePostal }}</td>
						<td>{{ societe.ville }}</td>
						<td>{{ societe.pays }}</td>
						<td>{{ societe.commentaire }}</td>
					</tr>
				{% endfor %}
			</tbody>

			<tfoot>
			</tfoot>
		</table>

		<div id="contacts" data-path="{{ path('societe_contact') }}">
		</div>
	</div>
{% endblock %}

src/AppBundle/Resources/views/Admin/menu.html.twig
{# src/AppBundle/Resources/views/Admin/menu.html.twig #}

<ul class="nav nav-pills nav-stacked">
	<li>
		<a href="{{ path('accueil_admin') }}">Accueil</a>
	</li>
    <li>
    	<a href="{{ path('gerer_compte') }}">Comptes</a>
    </li>
    <li>
    	<a href="{{ path('gerer_droits') }}">Droits</a>
    </li>
</ul>

src/AppBundle/Resources/views/Admin/selcontact.html.twig
{# src/AppBundle/Resources/view/Admin/selcontact.html.twig #}

<select id="selectcontact" class="form-control sel-largeur">
    <option value="-1" selected>Choisissez un contact</option>
    {% for contact in listecontact %}
        <option value="{{ contact.utilisateur.id }}">{{ contact.nomContact ~ ' ' ~ contact.prenomContact }}</option>
    {% endfor %}
</select>

src/AppBundle/Resources/views/Admin/utilisateur.html.twig
{# src/AppBundle/Resources/views/Admin/utilisateur.html.twig #}
{% extends "::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Admin - Compte
{% endblock %}

{% block breadcrumb %}
        <ol class="breadcrumb">
            <li><a href="{{ path('accueil_admin') }}">Administration</a></li>
            <li class="active">Compte</li>
        </ol>
{% endblock %}

{% block menu %}
    {{ render(controller("AppBundle:Admin:menu")) }}
{% endblock %}

{% block body %}
    <div id="cadrebody">
        {% if type == 'compte' %}
            {{ include('AppBundle:Admin:form_compte.html.twig', {'form': form, 'isdroit': true }) }}
        {% elseif type =='droits' %}
            {{ include('AppBundle:Admin:form_droits.html.twig', {'utilisateur': utilisateur, 'droits': droits}) }}
        {% endif %}        
    </div>
{% endblock %}